name: Checks

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: macos-12
    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme SerialDSL -sdk iphoneos -destination 'generic/platform=iOS' | xcpretty
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test
        run: xcodebuild -scheme SerialDSL -resultBundlePath results/SerialDSL.xcresult test -destination 'platform=iOS Simulator,name=iPhone 8,OS=16.0' -derivedDataPath ./DerivedData | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/SerialDSL.xcresult
        if: success() || failure()
