name: Checks

on:
  push:
    branches: "**"

jobs:
  swiftpm-build:
    runs-on: macos-12    
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
      - name: Swift Package
        run: swift build
        
  xcode-build:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
      - name: xcodebuild
        run: xcodebuild -scheme grain -sdk macosx -destination 'generic/platform=macos' | xcpretty

  test-render:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - name: Install mint
        run: brew install mint
      - name: Install grain
        run: mint install muukii/grain@${{ github.sha }}
      - name: Run
        run: /Users/runner/.mint/bin/grain
      
  test:
    runs-on: macos-12

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test
        run: xcodebuild -scheme GrainDescriptorTests test -sdk macosx -destination 'platform=macos' -derivedDataPath ./DerivedData | xcpretty

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: |
            results/SerialDSL.xcresult
        if: success() || failure()
